### ISSUE TITLE
Can't search a UTF-8 string on Ruby 1.9

### ISSUE THREAD

**Issue by kuroda** [danlucraft/rak#10]
I got following error messages when I tried to search a UTF-8 string like `☃` using rak:

<pre>
/home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak (666):12:in `scan': incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak (666):12:in `block in match_file'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak (666):10:in `each_line'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak (666):10:in `match_file'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:380:in `block in search'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:414:in `find_all_files'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:420:in `block in find_all_files'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:416:in `each'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:416:in `find_all_files'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:420:in `block in find_all_files'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:416:in `each'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:416:in `find_all_files'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:449:in `block in each_file'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:448:in `each'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:448:in `each_file'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:374:in `search'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/gems/rak-1.3/bin/rak:780:in `<top (required)>'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/bin/rak:19:in `load'
    from /home/kuroda/.rvm/gems/ruby-1.9.3-p0/bin/rak:19:in `<main>'
</pre>

On Ruby 1.8.7, the same search is executed perfectly.

**Comment by kuroda** [comment]
Should be solved by https://github.com/danlucraft/rak/pull/11

**Comment by danlucraft** [comment]
Hang on, my encoding knowledge is not that great, but doesn't this negate the effect of the earlier commit to force rak to treat everything as binary?
