### ISSUE TITLE
Support multi-location RC files

### ISSUE THREAD

**Issue by pvdb** [danlucraft/rak#20]
Similar to what `ack` does:

http://beyondgrep.com/documentation/ack-2.04-man.html#ackrc_location_semantics

Note: multi-location is important, so that you can have a global one in your home directory, but project-specific should be possible as well.

/cc @taw

**Comment by taw** [comment]
Our specific use case is related to https://github.com/danlucraft/rak/issues/19 but I'm sure other people will find other uses for that.
