### ISSUE TITLE
rak hangs forever if there is a pipe present

### ISSUE THREAD

**Issue by josh-m-sharpe** [danlucraft/rak#7]
If there is a lingering pipe left over (say from my test suite) then rak will hang forever and not return a response.

You should be able to reproduce with this:
~/RAILS_ROOT/ $ mkfifi some_pipe
~/RAILS_ROOT/ $ rak class

...and hang

~/RAILS_ROOT/ $ rm some_pipe
~/RAILS_ROOT/ $ rak class
... works fine

**Comment by danlucraft** [comment]
Seems to work ok now, at least when I am testing with mkfifo.
